[package]
name = "neko"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["json", "macros"] }
serde = "1.0.216"
serde_derive = "1.0.216"
serde_json = "1.0.134"
tokio = { version = "1.42.0", features = ["full"] }
